version: "3"

services:
  app:  
    image: node:12-alpine
    container_name: phu-monitoring-nodejs
    restart: unless-stopped
    
    volumes:
      - ./:/myapp
    
    working_dir: /myapp
    
    #environment:
    #  NODE_ENV: development
    
    ports:
      - 6003:3000
    
    command: >
        sh -c "npm install && npm run dev"
    #command: sh -c "npm install -g pm2 && npm install && pm2-runtime server.js --watch"
    #command: npm run start              
    #command: npm run dev

    # networks:
    #     myip:
    #       ipv4_address: 10.0.75.1

# networks:
#     myip:
#         driver: bridge
#         ipam:
#             config:
#                 - subnet: 10.0.75.0/16
#                   gateway: 